In [ ]:
import cv2
import numpy as np
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
image_path = '/content/DIP_Lab_task_02.jpg'

In [ ]:
rgb_image = cv2.imread(image_path)
if rgb_image is None:
    print("Error: Image not found. Check the path.")
else:
    gray_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2GRAY)
    print("Successfully converted RGB image to grayscale.")

    x, y = 50, 50
    sub_region = gray_image[y:y+5, x:x+5]

    print("Extracted 5x5 Sub-region of Grayscale Image:")
    print(sub_region)


Successfully converted RGB image to grayscale.
Extracted 5x5 Sub-region of Grayscale Image:
[[106 107 108 109 107]
 [114 115 113 114 112]
 [118 119 118 118 116]
 [120 120 121 120 118]
 [122 122 120 120 119]]
